In [ ]:
import numpy as np
import pandas as pd
import sklearn

In [ ]:
dt=pd.read_csv('/content/Churn_Modelling.csv')
X=dt.drop('Exited',axis=1)
y = dt.Exited
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64


In [ ]:
dt.shape

(10000, 14)

**Data Preprocessing**

In [ ]:
dt.info

<bound method DataFrame.info of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfP

In [ ]:
dt.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
X=X.drop("Surname",axis=1)
X=X.drop("RowNumber",axis=1)
X=X.drop("CustomerId",axis=1)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
labels=le.fit_transform(X['Gender'])
print(labels)
X['Gender']=labels
print(X['Gender'])

[0 0 0 ... 0 1 0]
0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64


In [ ]:
labels=le.fit_transform(X['Geography'])
print(labels)
X['Geography']=labels
print(X['Geography'])

[0 2 0 ... 0 1 0]
0       0
1       2
2       0
3       0
4       2
       ..
9995    0
9996    0
9997    0
9998    1
9999    0
Name: Geography, Length: 10000, dtype: int64


In [ ]:
X['Balance']=X['Balance'].astype(int)
print(X['Balance'])

0            0
1        83807
2       159660
3            0
4       125510
         ...  
9995         0
9996     57369
9997         0
9998     75075
9999    130142
Name: Balance, Length: 10000, dtype: int64


In [ ]:
X['EstimatedSalary']=X['EstimatedSalary'].astype(int)
print(X['EstimatedSalary'])

0       101348
1       112542
2       113931
3        93826
4        79084
         ...  
9995     96270
9996    101699
9997     42085
9998     92888
9999     38190
Name: EstimatedSalary, Length: 10000, dtype: int64


In [ ]:
X.head()

CreditScore  Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          619          0       0   42       2        0              1   
1          608          2       0   41       1    83807              1   
2          502          0       0   42       8   159660              3   
3          699          0       0   39       1        0              2   
4          850          2       0   43       2   125510              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1           101348  
1          0               1           112542  
2          1               0           113931  
3          0               0            93826  
4          1               1            79084

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  int64
 2   Gender           10000 non-null  int64
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  int64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  int64
dtypes: int64(10)
memory usage: 781.4 KB


**Test and Train Sample**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train[0])
print(X_test[0])
print(y_train[0])

[ 0.16958176  1.51919821 -1.09168714 -0.46460796  0.00666099 -1.21571672
  0.8095029   0.64259497 -1.03227043  1.10642907]
[-0.55204276  0.3131264  -1.09168714 -0.36890377  1.04473698  0.87931039
 -0.92159124  0.64259497  0.9687384   1.61085395]
1


KeyError: ignored

**KNN Classifier**

In [ ]:
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier
KNNclassifier=KNeighborsClassifier(n_neighbors=5,metric='manhattan')
KNNclassifier.fit(X_train,y_train)

KNeighborsClassifier(metric='manhattan')

In [ ]:
y_pred=KNNclassifier.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
KNN_Confusion_Matrix=confusion_matrix(y_test,y_pred)
KNN_Accuracy_Score=accuracy_score(y_test,y_pred)
print("KNN Accuracy Score:",KNN_Accuracy_Score)
print("KNN Confusion Matrix:")
KNN_Confusion_Matrix

KNN Accuracy Score: 0.8375
KNN Confusion Matrix:


array([[1504,   91],
       [ 234,  171]])

In [ ]:
KNN_Precision=metrics.precision_score(y_test,y_pred)
KNN_Recall=metrics.recall_score(y_test,y_pred)
print("KNN Precision:",KNN_Precision)
print("KNN Recall:",KNN_Recall)

KNN Precision: 0.6526717557251909
KNN Recall: 0.4222222222222222


**SVM Classifier**

In [ ]:
from sklearn import svm
SVMclassifier=svm.SVC(kernel='linear')
SVMclassifier.fit(X_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred=SVMclassifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
SVM_Confusion_Matrix=confusion_matrix(y_test,y_pred)
SVM_Accuracy_Score=accuracy_score(y_test,y_pred)
print("SVM Accuracy Score:",SVM_Accuracy_Score)
print("SVM Confusion Matrix:")
SVM_Confusion_Matrix

SVM Accuracy Score: 0.7975
SVM Confusion Matrix:


array([[1595,    0],
       [ 405,    0]])

In [ ]:
SVM_Precision=metrics.precision_score(y_test,y_pred)
SVM_Recall=metrics.recall_score(y_test,y_pred)
print("SVM Precision:",SVM_Precision)
print("SVM Recall:",SVM_Recall)

SVM Precision: 0.0
SVM Recall: 0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Naive Bayes Classifier**

In [ ]:
from sklearn.naive_bayes import GaussianNB
NBClassifier=GaussianNB()
NBClassifier.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=NBClassifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
NB_Confusion_Matrix=confusion_matrix(y_test,y_pred)
NB_Accuracy_Score=accuracy_score(y_test,y_pred)
print("NB Accuracy Score:",NB_Accuracy_Score)
print("NB Confusion Matrix:")
NB_Confusion_Matrix

NB Accuracy Score: 0.8275
NB Confusion Matrix:


array([[1548,   47],
       [ 298,  107]])

In [ ]:
NB_Precision=metrics.precision_score(y_test,y_pred)
NB_Recall=metrics.recall_score(y_test,y_pred)
print("Precision:",NB_Precision)
print("Recall:",NB_Recall)

Precision: 0.6948051948051948
Recall: 0.2641975308641975


**Decision Tree Classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier  
DTclassifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
DTclassifier.fit(X_train, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred=DTclassifier.predict(X_test)
y_pred

array([1, 1, 0, ..., 0, 0, 0])

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
DT_Confusion_Matrix=confusion_matrix(y_test,y_pred)
DT_Accuracy_Score=accuracy_score(y_test,y_pred)
print("Decision Tree Classifier Accuracy Score:",DT_Accuracy_Score)
print("Decision Tree Classifier Confusion Matrix:")
DT_Confusion_Matrix

Decision Tree Classifier Accuracy Score: 0.788
Decision Tree Classifier Confusion Matrix:


array([[1369,  226],
       [ 198,  207]])

In [ ]:
DT_Precision=metrics.precision_score(y_test,y_pred)
DT_Recall=metrics.recall_score(y_test,y_pred)
print("Precision:",DT_Precision)
print("Recall:",DT_Recall)

Precision: 0.4780600461893764
Recall: 0.5111111111111111


**Comparison **

In [ ]:
#KNN Classifier
print("KNN Accuracy Score:",KNN_Accuracy_Score)
#SVM Classifier
print("SVM Accuracy Score:",SVM_Accuracy_Score)
#Naive Bayes Classifier
print("NB Accuracy Score:",NB_Accuracy_Score)
#Decision Tree Classifier
print("Decision Tree Classifier Accuracy Score:",DT_Accuracy_Score)

KNN Accuracy Score: 0.8375
SVM Accuracy Score: 0.7975
NB Accuracy Score: 0.8275
Decision Tree Classifier Accuracy Score: 0.788


In [ ]:
#KNN Classifier
print("KNN Precision:",KNN_Precision)
print("KNN Recall:",KNN_Recall)
#SVM Classifier
print("SVM Precision:",SVM_Precision)
print("SVM Recall:",SVM_Recall)
#Naive Bayes Classifier
print("Naive Bayes Precision:",NB_Precision)
print("Naive Bayes Recall:",NB_Recall)
#Decision Tree Classifier
print(" Decision Tree Classifier Precision:",DT_Precision)
print("Decision Tree Classifier Recall:",DT_Recall)

KNN Precision: 0.6526717557251909
KNN Recall: 0.4222222222222222
SVM Precision: 0.0
SVM Recall: 0.0
Naive Bayes Precision: 0.6948051948051948
Naive Bayes Recall: 0.2641975308641975
 Decision Tree Classifier Precision: 0.4780600461893764
Decision Tree Classifier Recall: 0.5111111111111111
