<a href="https://colab.research.google.com/github/vaisakh678/dm/blob/main/Copy_of_Copy_of_titanicGS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from numpy import mean
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
dataset=pd.read_csv('/content/titanic.csv')

In [ ]:
dataset=dataset.drop(['PassengerId','Cabin','Name','Ticket'],axis=1)
dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
dataset["Sex"] = dataset.Sex.apply(lambda  x:0 if x=='female' else 1)
dataset.head(10)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S
5         0       3    1   NaN      0      0   8.4583        Q
6         0       1    1  54.0      0      0  51.8625        S
7         0       3    1   2.0      3      1  21.0750        S
8         1       3    0  27.0      0      2  11.1333        S
9         1       2    0  14.0      1      0  30.0708        C

In [ ]:
dataset=dataset.fillna(dataset.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


In [ ]:
dataset['Age'] = dataset['Age'].astype('int')

In [ ]:
common_value = 'S'
dataset['Embarked'] = dataset['Embarked'].fillna(common_value)

In [ ]:
label_encoder = preprocessing.LabelEncoder()
dataset.Embarked= label_encoder.fit_transform(dataset.Embarked)

In [ ]:
dataset['Fare'] = dataset['Fare'].fillna(0)
dataset['Fare'] = dataset['Fare'].astype(int)

In [ ]:
x=dataset.iloc[:,[1,2,3,4,5,6,7]].values
y=dataset.iloc[:,0].values
x[0]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)
print(x_train[0])
print(x_test[0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train[0])
print(x_test[0])

In [ ]:
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

In [ ]:
y_pred=classifier.predict(x_test)
y_pred

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
scores = cross_val_score(classifier, x,y, cv=cv)
print((mean(scores)))

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

In [ ]:
#model precision : what percentage of positive tuples are labelled as such
print('Precision: ',metrics.precision_score(y_test,y_pred))

#model recall : what percentage of positive tuples are labelled as such
print('Recall: ',metrics.recall_score(y_test,y_pred))

Precision:  0.7966101694915254
Recall:  0.6811594202898551


In [ ]:
#implement SVM model
#import svm model
from sklearn import svm

# create a  svm classifier

clf=svm.SVC(kernel='linear') #linear kernal

#train the mode using the trainig sets
clf.fit(x_train,y_train)

#predit the response for test dataset


y_pred=clf.predict(x_test)

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
scores = cross_val_score(clf, x,y, cv=cv)
print((mean(scores)))

0.7867679367271359


In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[92, 18],
       [20, 49]])

In [ ]:
#model precision:what percentage of positive tuples are labeled as such?
print("precision:",metrics.precision_score(y_test,y_pred))

#model recall:what percentage of positive tuples are labeled as such?
print("recall:",metrics.recall_score(y_test,y_pred))

precision: 0.7313432835820896
recall: 0.7101449275362319


In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(x_train,y_train)
y_pred=tree.predict(x_test)

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
scores = cross_val_score(tree, x,y, cv=cv)
print((mean(scores)))

0.7890276818780994


In [ ]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[100,  10],
       [ 22,  47]])

In [ ]:
#model precision:what percentage of positive tuples are labeled as such?
print("precision:",metrics.precision_score(y_test,y_pred))

#model recall:what percentage of positive tuples are labeled as such?
print("recall:",metrics.recall_score(y_test,y_pred))

precision: 0.8245614035087719
recall: 0.6811594202898551


In [ ]:
from sklearn.naive_bayes import GaussianNB
gaussian=GaussianNB()
gaussian.fit(x_train,y_train)
y_pred=gaussian.predict(x_test)

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
scores = cross_val_score(gaussian, x,y, cv=cv)
print((mean(scores)))

0.789033958947963


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc_guassian=round(gaussian.score(x_train,y_train)*100,2)
cm

array([[87, 23],
       [15, 54]])

In [ ]:
#model precision:what percentage of positive tuples are labeled as such?
print("precision:",metrics.precision_score(y_test,y_pred))

#model recall:what percentage of positive tuples are labeled as such?
print("recall:",metrics.recall_score(y_test,y_pred))

precision: 0.7012987012987013
recall: 0.782608695652174
